<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20150913232631.1"><vh>@settings</vh>
<v t="amd.20150913232631.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20150913232631.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20150919102739.1"><vh>專案架構</vh>
<v t="amd.20150919113520.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20151007224830.1"><vh>Jupyter 安裝與執行</vh></v>
<v t="amd.20150919103357.1"><vh>pelican 設定</vh></v>
</v>
<v t="amd.20151009065821.1"><vh>@edit README.md</vh></v>
<v t="amd.20150919113957.1" a="E"><vh>以下為 pelican 文章</vh>
<v t="amd.20150919124128.1"><vh>@button pelican content</vh></v>
<v t="amd.20150919114010.1" a="E"><vh>@path pelican</vh>
<v t="amd.20151006130205.1"><vh>@edit publishconf.py</vh></v>
<v t="amd.20151006113136.1" a="E"><vh>@path content</vh>
<v t="amd.20150919114035.1"><vh>@edit simplest.md</vh></v>
<v t="leo.20151112233718.1"><vh>@edit 2015cphww8.md</vh></v>
<v t="leo.20151113182440.1"><vh>@edit 2015cphww7.md</vh></v>
<v t="leo.20151113182442.1"><vh>@edit 2015cphww6.md</vh></v>
<v t="leo.20151113171828.1"><vh>@edit 2015cphww5.md</vh></v>
<v t="leo.20151113182017.1"><vh>@edit 2015cphww4.md</vh></v>
<v t="leo.20151113012153.1"><vh>@edit 2015cphww3.md</vh></v>
<v t="leo.20151113005706.1"><vh>@edit 2015cphww2.md</vh></v>
<v t="leo.20151113003814.1"><vh>@edit 2015cphww1.md</vh></v>
<v t="amd.20150920000911.1"><vh>@edit 2015cpnote1.md</vh></v>
</v>
</v>
</v>
<v t="amd.20150919120205.1" a="E"><vh>以下為 reveal 投影片</vh>
<v t="amd.20150915155634.1"><vh>@clean cadpaw1.html</vh>
<v t="amd.20150915155634.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915155634.3" a="E"><vh>head</vh>
<v t="amd.20150915155634.4"><vh>title - 標題</vh></v>
<v t="amd.20150915155634.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915155634.7"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915155634.8" a="E"><vh>body</vh>
<v t="amd.20150915155634.9" a="E"><vh>div - reveal</vh>
<v t="amd.20150915155634.10" a="E"><vh>div - slides</vh>
<v t="amd.20150915155634.11"><vh>h1 - 課程說明</vh></v>
<v t="amd.20150915172241.1"><vh>h1 - 開放自評規劃</vh></v>
<v t="amd.20150915155634.12"><vh>h2 - 實體輔助工具</vh></v>
<v t="amd.20150915155634.13"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915155634.14"><vh>h2</vh></v>
<v t="amd.20150915155634.15"><vh>h2</vh></v>
<v t="amd.20150915155634.16"><vh>h2</vh></v>
</v>
<v t="amd.20150915173703.1"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915173703.2" a="E"><vh>pre</vh>
<v t="amd.20150915173703.3"><vh>code</vh></v>
</v>
<v t="amd.20150915173703.4"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.17"><vh>h2</vh></v>
<v t="amd.20150915204710.1"><vh>內嵌 Vimeo 影片</vh></v>
<v t="amd.20150915155634.18"><vh>h2</vh></v>
<v t="amd.20150915155634.19"><vh>h2</vh></v>
<v t="amd.20150915155634.20"><vh>markdown 頁面</vh></v>
<v t="amd.20150915155634.21" a="E"><vh>h2</vh>
<v t="amd.20150915160450.1"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915155634.28" a="E"><vh>下屬頁面</vh>
<v t="amd.20150915161424.1"><vh>h2</vh></v>
<v t="amd.20150915155634.29"><vh>p</vh></v>
<v t="amd.20150915155634.30"><vh>p</vh></v>
<v t="amd.20150915155634.31"><vh>p</vh></v>
<v t="amd.20150915155634.32"><vh>p</vh></v>
<v t="amd.20150915155634.33"><vh>p</vh></v>
<v t="amd.20150915155634.34"><vh>p</vh></v>
<v t="amd.20150915155634.35"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915155634.36"><vh>h2</vh></v>
<v t="amd.20150915155634.37"><vh>p</vh>
<v t="amd.20150915155634.38"><vh>a</vh></v>
<v t="amd.20150915155634.39"><vh>a</vh></v>
<v t="amd.20150915155634.40"><vh>a</vh></v>
<v t="amd.20150915155634.41"><vh>a</vh></v>
<v t="amd.20150915155634.42"><vh>a</vh></v>
<v t="amd.20150915155634.43"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.44"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915155634.45" a="E"><vh>p</vh>
<v t="amd.20150915155634.46"><vh>a</vh></v>
<v t="amd.20150915155634.47"><vh>a</vh></v>
<v t="amd.20150915155634.48"><vh>a</vh></v>
<v t="amd.20150915155634.49"><vh>a</vh></v>
<v t="amd.20150915155634.50"><vh>a</vh></v>
<v t="amd.20150915155634.51"><vh>a</vh></v>
<v t="amd.20150915155634.52"><vh>a</vh></v>
<v t="amd.20150915155634.53"><vh>a</vh></v>
<v t="amd.20150915155634.54"><vh>a</vh></v>
<v t="amd.20150915155634.55"><vh>a</vh></v>
<v t="amd.20150915155634.56"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.57"><vh>h2</vh></v>
<v t="amd.20150915155634.58"><vh>p</vh>
<v t="amd.20150915155634.59"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.60"><vh>a</vh></v>
<v t="amd.20150915155634.61"><vh>h2</vh></v>
<v t="amd.20150915155634.62" a="E"><vh>pre</vh>
<v t="amd.20150915155634.63"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.64"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915155634.65" a="E"><vh>pre</vh>
<v t="amd.20150915155634.66"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.67" a="E"><vh>div</vh>
<v t="amd.20150915155634.68"><vh>h2</vh></v>
<v t="amd.20150915155634.69"><vh>pre</vh>
<v t="amd.20150915155634.70"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915155634.71"><vh>h2</vh></v>
<v t="amd.20150915155634.72"><vh>h2</vh></v>
<v t="amd.20150915155634.73"><vh>p</vh></v>
<v t="amd.20150915155634.74"><vh>pre</vh>
<v t="amd.20150915155634.75"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.76"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915155634.77"><vh>p</vh></v>
<v t="amd.20150915155634.78" a="E"><vh>pre</vh>
<v t="amd.20150915155634.79"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.80" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915155634.81" a="E"><vh>pre</vh>
<v t="amd.20150915155634.82"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.83"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.85"><vh>h2</vh></v>
<v t="amd.20150915155634.86" a="E"><vh>ul</vh>
<v t="amd.20150915155634.87"><vh>li</vh></v>
<v t="amd.20150915155634.88"><vh>li</vh></v>
<v t="amd.20150915155634.89"><vh>li</vh></v>
<v t="amd.20150915155634.90"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.91"><vh>h2</vh></v>
<v t="amd.20150915155634.92"><vh>ol</vh>
<v t="amd.20150915155634.93"><vh>li</vh></v>
<v t="amd.20150915155634.94"><vh>li</vh></v>
<v t="amd.20150915155634.95"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.96"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915155634.97" a="E"><vh>table</vh>
<v t="amd.20150915155634.98"><vh>thead</vh>
<v t="amd.20150915155634.99"><vh>tr</vh>
<v t="amd.20150915155634.100"><vh>th</vh></v>
<v t="amd.20150915155634.101"><vh>th</vh></v>
<v t="amd.20150915155634.102"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915155634.103"><vh>tbody</vh>
<v t="amd.20150915155634.104"><vh>tr</vh>
<v t="amd.20150915155634.105"><vh>td</vh></v>
<v t="amd.20150915155634.106"><vh>td</vh></v>
<v t="amd.20150915155634.107"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.108"><vh>tr</vh>
<v t="amd.20150915155634.109"><vh>td</vh></v>
<v t="amd.20150915155634.110"><vh>td</vh></v>
<v t="amd.20150915155634.111"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.112"><vh>tr</vh>
<v t="amd.20150915155634.113"><vh>td</vh></v>
<v t="amd.20150915155634.114"><vh>td</vh></v>
<v t="amd.20150915155634.115"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.116"><vh>h2</vh></v>
<v t="amd.20150915155634.117"><vh>p</vh>
<v t="amd.20150915155634.118"><vh>q</vh></v>
</v>
<v t="amd.20150915155634.119"><vh>blockquote</vh></v>
<v t="amd.20150915155634.120"><vh>h2</vh></v>
<v t="amd.20150915155634.121"><vh>p</vh>
<v t="amd.20150915155634.122"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.123"><vh>h2</vh></v>
<v t="amd.20150915155634.124" a="E"><vh>p</vh>
<v t="amd.20150915155634.125"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.126"><vh>p</vh>
<v t="amd.20150915155634.127"><vh>em</vh></v>
</v>
<v t="amd.20150915155634.128"><vh>h2</vh></v>
<v t="amd.20150915155634.129"><vh>p</vh>
<v t="amd.20150915155634.130"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.131"><vh>iframe</vh></v>
<v t="amd.20150915155634.132"><vh>h2</vh></v>
<v t="amd.20150915155634.133" a="E"><vh>p</vh>
<v t="amd.20150915155634.134"><vh>code</vh></v>
<v t="amd.20150915155634.135"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.136"><vh>h2</vh></v>
<v t="amd.20150915155634.137"><vh>p</vh>
<v t="amd.20150915155634.138"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.139"><vh>pre</vh>
<v t="amd.20150915155634.140"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.141"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915155634.142"><vh>p</vh></v>
<v t="amd.20150915155634.143" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915155634.148"><vh>li</vh>
<v t="amd.20150915155634.149"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.150"><vh>li</vh>
<v t="amd.20150915155634.151"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.152"><vh>li</vh>
<v t="amd.20150915155634.153"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.146"><vh>li</vh>
<v t="amd.20150915155634.147"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.145"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.154"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915155634.158"><vh>script</vh></v>
<v t="amd.20150915155634.159"><vh>script</vh></v>
<v t="amd.20150915155634.160"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150913233943.1"><vh>@clean cadpbw1.html</vh>
<v t="amd.20150913233943.2" a="E"><vh>html</vh>
<v t="amd.20150913233943.3" a="E"><vh>head</vh>
<v t="amd.20150913233943.4"><vh>title</vh></v>
</v>
<v t="amd.20150913233943.5" a="E"><vh>body</vh>
<v t="amd.20150913233943.6" a="E"><vh>div</vh>
<v t="amd.20150913233943.7" a="E"><vh>div</vh>
<v t="amd.20150913234947.1"><vh>title page</vh>
<v t="amd.20150913235225.1"><vh>標題頁下的子頁</vh></v>
</v>
<v t="amd.20150913235034.1"><vh>本日要點</vh></v>
<v t="amd.20150914000138.1"><vh>Anaconda Python</vh></v>
<v t="amd.20150914000332.1" a="E"><vh>設計的表達方式</vh>
<v t="amd.20150914000332.2"><vh>協同模式下的網際雲端內容呈現</vh></v>
</v>
<v t="amd.20150913235123.1"><vh>結論</vh></v>
</v>
</v>
<v t="amd.20150913233943.81"><vh>script</vh></v>
<v t="amd.20150913233943.82"><vh>script</vh></v>
<v t="amd.20150913233943.83"><vh>script</vh></v>
</v>
</v>
</v>
<v t="ibm.20150918175403.1"><vh>@clean cpw1.html</vh>
<v t="ibm.20150918175403.2"><vh>檔案說明</vh></v>
<v t="ibm.20150918175403.3" a="E"><vh>html 標註</vh>
<v t="ibm.20150918175403.4" a="E"><vh>body 標註</vh>
<v t="ibm.20150918175403.5" a="E"><vh>div class="reveal"</vh>
<v t="ibm.20150918175403.6" a="E"><vh>div class="slides"</vh>
<v t="ibm.20150918175403.7"><vh>有關我的作業</vh></v>
<v t="ibm.20150918175403.8"><vh>課程規劃</vh></v>
<v t="ibm.20150918175403.9"><vh>作業規劃</vh></v>
<v t="ibm.20150918175711.1"><vh>Git 操作</vh></v>
<v t="ibm.20150918175951.1"><vh>Jupyter 操作</vh></v>
<v t="ibm.20150918181528.1"><vh>結論</vh></v>
</v>
</v>
<v t="ibm.20150918175403.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915211341.1"><vh>@clean simplest.html</vh>
<v t="amd.20150917085040.1"><vh>檔案說明</vh></v>
<v t="amd.20150915211351.1" a="E"><vh>html 標註</vh>
<v t="amd.20150915211351.4" a="E"><vh>body 標註</vh>
<v t="amd.20150915211351.5" a="E"><vh>div class="reveal"</vh>
<v t="amd.20150915211351.6" a="E"><vh>div class="slides"</vh>
<v t="amd.20150915211351.7"><vh>有關我的作業</vh></v>
<v t="amd.20150915211351.9"><vh>作業任務一</vh></v>
<v t="amd.20150915211351.12"><vh>第3張投影片</vh></v>
</v>
</v>
<v t="amd.20150915211351.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151112231403.1"><vh>@clean W8.html</vh>
<v t="leo.20151112231403.2"><vh>檔案說明</vh></v>
<v t="leo.20151112231403.3"><vh>html 標註</vh>
<v t="leo.20151112231403.4" a="E"><vh>body 標註</vh>
<v t="leo.20151112231403.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151112231403.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151112231403.7"><vh>有關我的作業</vh></v>
<v t="leo.20151112231702.1"><vh>內容大綱</vh></v>
<v t="leo.20151112231403.8"><vh>什麼是IPv4?</vh></v>
<v t="leo.20151113000709.1"><vh>什麼是IPv6?</vh></v>
<v t="leo.20151113000951.1"><vh>IPv6和IPv4比較</vh></v>
<v t="leo.20151112231403.9"><vh>心得感想</vh></v>
<v t="leo.20151116202754.1"><vh>自評成績</vh></v>
</v>
</v>
<v t="leo.20151112231403.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151113171819.1"><vh>@clean W7.html</vh>
<v t="leo.20151113171819.2"><vh>檔案說明</vh></v>
<v t="leo.20151113171819.3" a="E"><vh>html 標註</vh>
<v t="leo.20151113171819.4" a="E"><vh>body 標註</vh>
<v t="leo.20151113171819.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151113171819.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151113171819.7"><vh>有關我的作業</vh></v>
<v t="leo.20151113171819.8"><vh>內容大綱</vh></v>
<v t="leo.20151113171819.9"><vh>協同倉儲</vh></v>
<v t="leo.20151116000536.1"><vh>缺點</vh></v>
<v t="leo.20151113171819.11"><vh>解決方法</vh></v>
<v t="leo.20151113171819.12"><vh>心得感想</vh></v>
<v t="leo.20151113181636.1"><vh>自評成績</vh></v>
</v>
</v>
<v t="leo.20151113171819.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151113182428.1"><vh>@clean W6.html</vh>
<v t="leo.20151113182428.2"><vh>檔案說明</vh></v>
<v t="leo.20151113182428.3" a="E"><vh>html 標註</vh>
<v t="leo.20151113182428.4" a="E"><vh>body 標註</vh>
<v t="leo.20151113182428.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151113182428.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151113182428.7"><vh>有關我的作業</vh></v>
<v t="leo.20151113182428.8"><vh>內容大綱</vh></v>
<v t="leo.20151113182428.9"><vh>補充Python</vh></v>
<v t="leo.20151116192551.1"><vh>問題與討論</vh></v>
<v t="leo.20151113182428.12"><vh>心得感想</vh></v>
<v t="leo.20151113182428.13"><vh>自評成績</vh></v>
</v>
</v>
<v t="leo.20151113182428.14"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151113182002.1"><vh>@clean W5.html</vh>
<v t="leo.20151113182002.2"><vh>檔案說明</vh></v>
<v t="leo.20151113182002.3" a="E"><vh>html 標註</vh>
<v t="leo.20151113182002.4" a="E"><vh>body 標註</vh>
<v t="leo.20151113182002.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151113182002.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151113182002.7"><vh>有關我的作業</vh></v>
<v t="leo.20151113182002.8"><vh>內容大綱</vh></v>
<v t="leo.20151113182002.9"><vh>GitHub使用</vh></v>
<v t="leo.20151116213351.1"><vh>為什麼使用GitHub?</vh></v>
<v t="leo.20151113182002.10"><vh>為什麼使用GitHub?1</vh></v>
<v t="leo.20151113182002.11"><vh>Git基本操作</vh></v>
<v t="leo.20151116230132.1"><vh>Git基本操作1</vh></v>
<v t="leo.20151113182002.12"><vh>心得感想</vh></v>
<v t="leo.20151113182002.13"><vh>自評成績</vh></v>
</v>
</v>
<v t="leo.20151113182002.14"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151113015646.1"><vh>@clean W4.html</vh>
<v t="leo.20151113015646.2"><vh>檔案說明</vh></v>
<v t="leo.20151113015646.3" a="E"><vh>html 標註</vh>
<v t="leo.20151113015646.4" a="E"><vh>body 標註</vh>
<v t="leo.20151113015646.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151113015646.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151113015646.7"><vh>有關我的作業</vh></v>
<v t="leo.20151113015646.8"><vh>內容大綱</vh></v>
<v t="leo.20151113015646.9"><vh>LEO?</vh></v>
<v t="leo.20151113015646.10"><vh>LEO語言</vh></v>
<v t="leo.20151113015646.11"><vh>Jupyter</vh></v>
<v t="leo.20151113015646.12"><vh>心得感想</vh></v>
<v t="leo.20151113171612.1"><vh>自評成績</vh></v>
</v>
</v>
<v t="leo.20151113015646.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151113012225.1"><vh>@clean W3.html</vh>
<v t="leo.20151113012225.2"><vh>檔案說明</vh></v>
<v t="leo.20151113012225.3" a="E"><vh>html 標註</vh>
<v t="leo.20151113012225.4" a="E"><vh>body 標註</vh>
<v t="leo.20151113012225.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151113012225.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151113012225.7"><vh>有關我的作業</vh></v>
<v t="leo.20151113012225.8"><vh>內容大綱</vh></v>
<v t="leo.20151113012225.9"><vh>Python</vh></v>
<v t="leo.20151113154922.1"><vh>為什麼使用python?</vh></v>
<v t="leo.20151113012225.11"><vh>Does anyone</vh></v>
<v t="leo.20151113012225.12"><vh>Python語言</vh></v>
<v t="leo.20151113154938.1"><vh>心得感想</vh></v>
<v t="leo.20151113160707.1"><vh>自評成績</vh></v>
</v>
</v>
<v t="leo.20151113012225.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151113005653.1"><vh>@clean W2.html</vh>
<v t="leo.20151113005653.2"><vh>檔案說明</vh></v>
<v t="leo.20151113005653.3" a="E"><vh>html 標註</vh>
<v t="leo.20151113005653.4" a="E"><vh>body 標註</vh>
<v t="leo.20151113005653.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151113005653.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151113005653.7"><vh>有關我的作業</vh></v>
<v t="leo.20151113005653.8"><vh>內容大綱</vh></v>
<v t="leo.20151113005653.9"><vh>Engineers</vh></v>
<v t="leo.20151113005653.10"><vh>What Engineers Do</vh></v>
<v t="leo.20151113005653.11"><vh>演變</vh></v>
<v t="leo.20151116212234.1"><vh>工程分支</vh></v>
<v t="leo.20151113005653.12"><vh>心得感想</vh></v>
<v t="leo.20151113161511.1"><vh>自評成績</vh></v>
</v>
</v>
<v t="leo.20151113005653.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151113003831.1"><vh>@clean W1.html</vh>
<v t="leo.20151113003831.2"><vh>檔案說明</vh></v>
<v t="leo.20151113003831.3" a="E"><vh>html 標註</vh>
<v t="leo.20151113003831.4" a="E"><vh>body 標註</vh>
<v t="leo.20151113003831.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151113003831.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151113003831.7"><vh>有關我的作業</vh></v>
<v t="leo.20151113003831.8"><vh>內容大綱</vh></v>
<v t="leo.20151113003831.9"><vh>第一堂課</vh></v>
<v t="leo.20151113003831.12"><vh>心得感想</vh></v>
</v>
</v>
<v t="leo.20151113003831.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.1"><vh>@clean v31ref.html</vh>
<v t="amd.20150915170743.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915170743.3"><vh>head</vh></v>
<v t="amd.20150915170743.7" a="E"><vh>body</vh>
<v t="amd.20150915170743.9" a="E"><vh>div - reveal and slides</vh>
<v t="amd.20150915170743.10"><vh>一般單頁加上 anchor</vh></v>
<v t="amd.20150915170743.11"><vh>一般單頁</vh></v>
<v t="amd.20150915170743.12" a="E"><vh>垂直有下屬頁</vh>
<v t="amd.20150915170743.13"><vh>下屬頁之一</vh></v>
<v t="amd.20150915170743.14"><vh>下屬頁之二</vh></v>
<v t="amd.20150915170743.15"><vh>下屬頁之三</vh></v>
</v>
<v t="amd.20150915170743.16"><vh>一般頁面加上跳頁 anchor</vh></v>
<v t="amd.20150915170743.19"><vh>markdown 頁面</vh></v>
<v t="amd.20150915170743.20" a="E"><vh>逐一出現項目頁面</vh>
<v t="amd.20150915170743.21"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915170743.22" a="E"><vh>垂直之下屬頁面</vh>
<v t="amd.20150915170743.23"><vh>標題</vh></v>
<v t="amd.20150915170743.24"><vh>一般項目</vh></v>
<v t="amd.20150915170743.25"><vh>逐一跳出項目 grow</vh></v>
<v t="amd.20150915170743.26"><vh>逐一跳出項目 shrink</vh></v>
<v t="amd.20150915170743.27"><vh>逐一跳出項目 fade-out</vh></v>
<v t="amd.20150915170743.28"><vh>逐一跳出項目 cruuent-visible</vh></v>
<v t="amd.20150915170743.29"><vh>逐一跳出項目 highlight-red</vh></v>
<v t="amd.20150915170743.30"><vh>逐一跳出項目 highlight-blue</vh></v>
</v>
</v>
<v t="amd.20150915170743.59"><vh>背景填圖頁面</vh></v>
<v t="amd.20150915170743.75" a="E"><vh>內含程式碼頁面</vh>
<v t="amd.20150915170743.76" a="E"><vh>pre</vh>
<v t="amd.20150915170743.77"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.78"><vh>p</vh></v>
</v>
<v t="amd.20150915170743.80" a="E"><vh>ul 資料表列</vh>
<v t="amd.20150915170743.81"><vh>li</vh></v>
<v t="amd.20150915170743.82"><vh>li</vh></v>
<v t="amd.20150915170743.83"><vh>li</vh></v>
<v t="amd.20150915170743.84"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.86" a="E"><vh>ol 資料表列</vh>
<v t="amd.20150915170743.87"><vh>li</vh></v>
<v t="amd.20150915170743.88"><vh>li</vh></v>
<v t="amd.20150915170743.89"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.91" a="E"><vh>表格頁面</vh>
<v t="amd.20150915170743.92" a="E"><vh>thead</vh>
<v t="amd.20150915170743.93" a="E"><vh>tr</vh>
<v t="amd.20150915170743.94"><vh>th</vh></v>
<v t="amd.20150915170743.95"><vh>th</vh></v>
<v t="amd.20150915170743.96"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915170743.97" a="E"><vh>tbody</vh>
<v t="amd.20150915170743.98"><vh>tr</vh>
<v t="amd.20150915170743.99"><vh>td</vh></v>
<v t="amd.20150915170743.100"><vh>td</vh></v>
<v t="amd.20150915170743.101"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.102"><vh>tr</vh>
<v t="amd.20150915170743.103"><vh>td</vh></v>
<v t="amd.20150915170743.104"><vh>td</vh></v>
<v t="amd.20150915170743.105"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.106"><vh>tr</vh>
<v t="amd.20150915170743.107"><vh>td</vh></v>
<v t="amd.20150915170743.108"><vh>td</vh></v>
<v t="amd.20150915170743.109"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.111" a="E"><vh>Clever Quotes</vh>
<v t="amd.20150915170743.112"><vh>q</vh></v>
<v t="amd.20150915170743.113"><vh>blockquote</vh></v>
</v>
<v t="amd.20150915170743.135"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915170743.137" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915170743.138"><vh>li</vh>
<v t="amd.20150915170743.139"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.140"><vh>li</vh>
<v t="amd.20150915170743.141"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.142"><vh>li</vh>
<v t="amd.20150915170743.143"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.144"><vh>li</vh>
<v t="amd.20150915170743.145"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.146"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.147"><vh>結束單頁</vh></v>
</v>
<v t="amd.20150915170743.148"><vh>script</vh></v>
</v>
</v>
</v>
</v>
<v t="leo.20151116223746.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20151116223746.3"><vh>Recovered node "自評成績" from @clean W8.html</vh>
<v t="leo.20151116223746.4"><vh>old:自評成績</vh></v>
<v t="leo.20151116223746.5"><vh>new:自評成績</vh></v>
</v>
</v>
<v t="leo.20151116231945.2" a="E"><vh>Recovered Nodes</vh>
<v t="leo.20151116231945.3"><vh>Recovered node "自評成績" from @clean W8.html</vh>
<v t="leo.20151116231945.4"><vh>old:自評成績</vh></v>
<v t="leo.20151116231945.5"><vh>new:自評成績</vh></v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20150913232631.1"></t>
<t tx="amd.20150913232631.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20150913232631.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20150913233943.1">@language xml
@tabwidth -4
@others
</t>
<t tx="amd.20150913233943.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150913233943.3">
&lt;head&gt;
@others
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;    
    &lt;!--Add support for earlier versions of Internet Explorer --&gt;
    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;
 
</t>
<t tx="amd.20150913233943.4">
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015 Fall CADP B Week1&lt;/title&gt;
</t>
<t tx="amd.20150913233943.5">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150913233943.6">
&lt;!-- Wrap the entire slide show in a div using the "reveal" class. --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.7">
&lt;!-- Wrap all slides in a single "slides" class --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.81">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
    </t>
<t tx="amd.20150913233943.82">&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
 
    </t>
<t tx="amd.20150913233943.83">&lt;script&gt;
        // Required, even if empty.
        Reveal.initialize({
        });
    &lt;/script&gt;
</t>
<t tx="amd.20150913234947.1">&lt;section id="title page"&gt;
&lt;section&gt;
標題頁面
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150913235034.1">&lt;section&gt;
本日要點
&lt;/section&gt;</t>
<t tx="amd.20150913235123.1">&lt;section&gt;
結論
&lt;/section&gt;</t>
<t tx="amd.20150913235225.1">&lt;section&gt;
標題頁下的子頁
&lt;/section&gt;</t>
<t tx="amd.20150914000138.1">&lt;section&gt;
&lt;a href="http://continuum.io/downloads"&gt;Anaconda Python 下載&lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150914000332.1">&lt;section id="設計的表達方式"&gt;
&lt;section&gt;
設計的表達方式
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150914000332.2">&lt;section&gt;
協同模式下的網際雲端內容呈現
&lt;/section&gt;</t>
<t tx="amd.20150915155634.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915155634.10">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.100">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915155634.101">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915155634.102">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915155634.103">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915155634.104">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915155634.105">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915155634.106">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.107">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.108">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915155634.109">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915155634.11">&lt;section id="fragments"&gt;
        &lt;h1&gt;課程說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;課程名稱: 電腦輔助設計實習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;開放 主動 自學與自評&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;使用 Solvespace 與 Creo 2.0&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;每週都有作業, 由各學員自評分數&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915155634.110">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.111">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.112">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915155634.113">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915155634.114">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.115">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.116">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.117">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.118">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915155634.119">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.12">&lt;section id="fragments"&gt;
    &lt;h2&gt;實體輔助工具&lt;/h2&gt;
    &lt;h3 class="fragment"&gt;電動折疊自行車&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;HP 伺服器&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;3D 印表機零件&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;其他需要採購工具?&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;先模擬分析, 再實際驗證?&lt;/h3&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.120">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.121">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.122">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915155634.123">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.124">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.125">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915155634.126">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.127">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915155634.128">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.129">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.13">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.130">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915155634.131">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.132">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.133">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.134">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915155634.135">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915155634.136">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.137">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.138">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915155634.139">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.14">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915155634.140">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915155634.141">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.142">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.143">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.145">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915155634.146">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.147">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915155634.148">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.149">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915155634.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.150">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.151">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915155634.152">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.153">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915155634.154">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915155634.158">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915155634.159">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915155634.16">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.160">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915155634.17">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.18">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.19">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915155634.20">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.21">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.28">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.29">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915155634.30">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.31">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.32">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.33">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.34">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.35">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915155634.36">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.37">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.38">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.39">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;2015 Fall 電腦輔助設計實習 甲班&lt;/title&gt;

</t>
<t tx="amd.20150915155634.40">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.41">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.42">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.43">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.44">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.45">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915155634.46">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.47">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.5">&lt;meta name="description" content="2015Fall CADP"&gt;
&lt;meta name="author" content="KMOL"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915155634.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915155634.52">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.53">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.54">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.55">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.56">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.57">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.58">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.59">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915155634.60">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915155634.61">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.62">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.63">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.64">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.65">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915155634.66">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915155634.67">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.68">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915155634.69">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915155634.7">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915155634.70">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.71">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.72">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.73">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.74">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915155634.75">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915155634.76">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.77">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.78">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.79">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.8">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915155634.80">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.81">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915155634.82">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915155634.83">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915155634.85">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.86">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.87">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915155634.88">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.89">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.9">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.90">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.91">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.92">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915155634.93">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915155634.94">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.95">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.96">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.97">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.98">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915155634.99">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915160450.1">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915161424.1">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915170743.10">&lt;section&gt;
    &lt;h1&gt;Reveal.js 使用說明&lt;/h1&gt;
    &lt;h3&gt;The HTML Presentation Framework 框架&lt;/h3&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / 
    &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;
    &lt;/small&gt;
    &lt;/p&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915170743.100">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.101">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.102">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915170743.103">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915170743.104">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.105">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.106">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915170743.107">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915170743.108">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.109">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.11">&lt;section&gt;
    &lt;h2&gt;Hello There&lt;/h2&gt;
    &lt;p&gt;
reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.111">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
    &lt;p&gt;
    @others
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.112">These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915170743.113">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
					</t>
<t tx="amd.20150915170743.12">&lt;section&gt;
&lt;h1&gt;以下為垂直頁面&lt;/h1&gt;
以下為垂直頁
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.13">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.135">&lt;section&gt;
    &lt;h2&gt;Take a Moment&lt;/h2&gt;
    &lt;p&gt;
    Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.137">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.138">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.139">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915170743.14">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.140">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.141">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915170743.142">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.143">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915170743.144">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.145">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915170743.146">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915170743.147">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.148">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // Full list of configuration options available at:
    // https://github.com/hakimel/reveal.js#configuration
    Reveal.initialize({
        controls: true,
        progress: true,
        history: true,
        center: true,

        transition: 'slide', // none/fade/slide/convex/concave/zoom

        // Optional reveal.js plugins
        dependencies: [
            { src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
            { src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
            { src: 'plugin/zoom-js/zoom.js', async: true },
            { src: 'plugin/notes/notes.js', async: true }
        ]
    });
&lt;/script&gt;

	

		
		</t>
<t tx="amd.20150915170743.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.16">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.19">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915170743.20">&lt;section&gt;
逐一出現
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.21">&lt;section id="fragments"&gt;
    &lt;h2&gt;Fragments&lt;/h2&gt;
    &lt;p&gt;Hit the next arrow...&lt;/p&gt;
    &lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
    &lt;p&gt;
        &lt;span class="fragment"&gt;... a&lt;/span&gt; 
        &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
        &lt;span class="fragment"&gt;slide.&lt;/span&gt;
    &lt;/p&gt;
    
    &lt;aside class="notes"&gt;
    This slide has fragments which are also stepped through in the notes window.
    &lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.22">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.23">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.24">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.25">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.26">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.27">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.28">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.29">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.3">&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;檔案標題&lt;/title&gt;
&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
&lt;meta name="author" content="作者"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;	
&lt;/head&gt;

</t>
<t tx="amd.20150915170743.30">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915170743.59">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
    &lt;pre&gt;
    &lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
    &lt;/code&gt;
    &lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.7">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915170743.75">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.76">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915170743.77">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915170743.78">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915170743.80">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.81">&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915170743.82">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.83">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.84">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.86">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
    &lt;ol&gt;
    @others
    &lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915170743.87">&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915170743.88">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.89">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.9">&lt;div class="reveal"&gt;
    &lt;!-- Any section element inside of this container is displayed as a slide --&gt;
    &lt;div class="slides"&gt;
    @others
    &lt;/div&gt;
&lt;/div&gt;



</t>
<t tx="amd.20150915170743.91">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
    &lt;table&gt;
    @others
    &lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.92">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915170743.93">&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.94">&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915170743.95">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915170743.96">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915170743.97">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915170743.98">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.99">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915172241.1">&lt;section id="fragments"&gt;
        &lt;h1&gt;自評說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;時效內的 Github 倉儲內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;完全開放的學員作業內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;彼此間可以互相學習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;存證內容: Github, copy.com, Vimeo 等&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;要怎麼收穫, 先怎麼栽!&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915173703.1">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915173703.2">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915173703.3">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915173703.4">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915204710.1">&lt;section&gt;
&lt;h1&gt;嵌入 Vimeo 影片&lt;/h1&gt;
&lt;iframe src="https://player.vimeo.com/video/137724068" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程系 KMOL&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915211341.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915211351.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="amd.20150915211351.12">&lt;section&gt;
    &lt;h1&gt;第3張投影片&lt;/h1&gt;
    &lt;p&gt;成績自評分數的量化依據?&lt;/p&gt;
    &lt;p&gt;可以連結到內部投影片&lt;a href="#/hw-task-one"&gt;作業任務一&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150915211351.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="amd.20150915211351.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915211351.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;有關我的作業&lt;/h1&gt;
    &lt;p&gt;學號姓名與日期&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="amd.20150915211351.9">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;作業任務一&lt;/h1&gt;
    &lt;p&gt;有關作業任務一的說明&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://www.google.com"&gt;Google&lt;/a&gt;
&lt;/section&gt;
				
</t>
<t tx="amd.20150917085040.1">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="amd.20150919102739.1">主要為 reveal.js 的簡報目錄架構, 其他子目錄為

images - 存放簡報與 pelican 網誌所需要的影像檔案

pelican - 存放 pelican 專案資料檔, 並且設法讓 pelican 所產生的 output 檔案直接存放到上層 reveal.js 根目錄

content/notebook - 存放 Jupyter 的 IPython notebook 檔案, 然後再由 pelican 設定, 將內容放入 blog 文章中

</t>
<t tx="amd.20150919103357.1">打算利用

pelican pelican -o ./../ -s publishconf.py

-o 指定 ouput 所在目錄, 這裡使用上一層目錄, 

-s 則指定 setting, 這裡採用 publishconf.py 中的設定

將位於專案中 pelican 目錄內的 .md 檔案, 轉為 html 網誌格式, 然後存在 reveal.js 的架構目錄中

也就是 index.html 是由 pelican 控制</t>
<t tx="amd.20150919113957.1"></t>
<t tx="amd.20150919114010.1"></t>
<t tx="amd.20150919120205.1"></t>
<t tx="amd.20150919124128.1">@language python
import os
#os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-bootstrap3")
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-octopress")
g.es("pelican 執行完畢")</t>
<t tx="amd.20151006113136.1"></t>
<t tx="amd.20151007224830.1">安裝

sudo pip3 install jupyter

執行

jupyter notebook
</t>
<t tx="ibm.20150918175403.1">@language xml
@tabwidth -4
@others

</t>
<t tx="ibm.20150918175403.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	</t>
<t tx="ibm.20150918175403.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="ibm.20150918175403.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015CP W1&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="ibm.20150918175403.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="ibm.20150918175403.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;計算機程式&lt;/h1&gt;
    &lt;p&gt;第1週教學內容&lt;/p&gt;		
&lt;/section&gt;
	</t>
<t tx="ibm.20150918175403.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;課程規劃&lt;/h1&gt;
    &lt;p&gt;教科書&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://openbookproject.net/thinkcs/python/english3e/"&gt;http://openbookproject.net/thinkcs/python/english3e/&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175403.9">&lt;section&gt;
    &lt;h1&gt;作業規劃&lt;/h1&gt;
    &lt;p&gt;影片內容&lt;/p&gt;
    &lt;a href="https://www.youtube.com/watch?v=9uq3w6JJS00"&gt;Zero to hero with Python&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175711.1">&lt;section&gt;
    &lt;h1&gt;Git 操作&lt;/h1&gt;
    &lt;p&gt;git clone&lt;/p&gt;
    &lt;p&gt;git config --global user.name&lt;/p&gt;
    &lt;p&gt;git config --global user.email&lt;/p&gt;
    &lt;p&gt;git add -A&lt;/p&gt;
    &lt;p&gt;git commit -m&lt;/p&gt;
    &lt;p&gt;git push&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918175951.1">&lt;section&gt;
    &lt;h1&gt;Jupyter 操作&lt;/h1&gt;
    &lt;p&gt;啟動&lt;/p&gt;
    &lt;p&gt;基本執行&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918181528.1">&lt;section&gt;
    &lt;h1&gt;結論&lt;/h1&gt;
    &lt;p&gt;自主開放學習&lt;/p&gt;
    &lt;p&gt;線上教材&lt;/p&gt;
    &lt;p&gt;影音教材&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="leo.20151112231403.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151112231403.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151112231403.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151112231403.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151112231403.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151112231403.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151112231403.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151112231403.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
  &lt;section&gt;

    &lt;h1&gt;第八週&lt;/h1&gt;
    &lt;p&gt;學號:40423104&lt;/p&gt;
    &lt;p&gt;姓名:Yan Syuan&lt;/p&gt;
    	
  &lt;/section&gt;
    
  &lt;section&gt;

    &lt;h1&gt;相信把這堂課學好會非常不一樣&lt;/h1&gt;
    
  &lt;/section&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="leo.20151112231403.8">&lt;section&gt;

    &lt;h1&gt;什麼是IPv4?&lt;/h1&gt;
    &lt;p&gt;是網際網路協定版本4&lt;/p&gt;
    &lt;p&gt;英文:Internet Protocol version 4&lt;/p&gt;
    &lt;p&gt;是網際網路協定的最新版本，用於封包交換網際網路的網路層協議&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151112231403.9">&lt;section&gt;
    &lt;h1&gt;心得感想&lt;/h1&gt;
    &lt;p&gt;在上課時，常常會聽到老師說IPv4和IPv6&lt;/p&gt;
    &lt;p&gt;所以決定在第八週介紹IPv4和IPv6&lt;/p&gt;
    &lt;p&gt;從這幾週當中我學到很多，很多高中沒接觸過的，也有很多讓我很難懂的，雖然從一開始的不懂到現在比較懂了，有8週的時，但在這段時間讓我越來越喜歡計算機程式這堂課了，很感謝老師給我們很多資料參考與學習，這些讓我對很多不會的東西大大改觀，雖然我的投影片和影片沒有細緻，但也是我每堂課跟著老師的步驟走的紀錄，希望自己在忘記步驟時，回去看一下自己的作法，再重新試試看，錯了就在修正，這樣我才會成長，最後一週，覺得時間過好快，期待每一週新的課程。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151112231702.1">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;內容大綱&lt;/h1&gt;
    &lt;p&gt;問題與討論&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;什麼是IPv4?&lt;/li&gt;
    &lt;li&gt;什麼是IPv6?&lt;/li&gt;
    &lt;li&gt;IPv6和IPv4比較&lt;/li&gt;
    &lt;li&gt;心得感想&lt;/li&gt;
    &lt;li&gt;自評成績&lt;/li&gt;
    &lt;/ul&gt;
    			
&lt;/section&gt;
	
</t>
<t tx="leo.20151113000709.1">&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;什麼是IPv6?&lt;/h1&gt;
    &lt;p&gt;是網際網路通訊協定第6版&lt;/p&gt;
    &lt;p&gt;英文:Internet Protocol version 6&lt;/p&gt;
    &lt;p&gt;IPv4為標準化網際網路的核心部分，也是使用最廣泛的網際網路協定版本&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113000951.1">&lt;section&gt;

    &lt;h1&gt;IPv6和IPv4比較&lt;/h1&gt;
    &lt;p&gt;IPv6定義了一種新的分組格式，目的是為了最小化路由器處理的報文首部IPv4為標準化網際網路的核心部分，也是使用最廣泛的網際網路協定版本，由於IPv4報文和IPv6報文首部有很大不同，因此這兩種協定無法互操作。大多數情況下，IPv6僅僅是對IPv4的一種保守擴充功能。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113003831.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151113003831.12">&lt;section&gt;
    &lt;h1&gt;心得感想&lt;/h1&gt;
    &lt;p&gt;聽不懂老師說什麼，讓我覺得我的計算機程式可能沒辦法過關&lt;/p&gt;
    &lt;p&gt;但是我知道，不會就要學習去問，所以我相信之後我對這堂課能有所改觀&lt;p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113003831.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151113003831.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151113003831.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151113003831.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151113003831.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113003831.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113003831.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
  &lt;section&gt;

    &lt;h1&gt;第一週報告&lt;/h1&gt;
    &lt;p&gt;學號:40423104&lt;/p&gt;
    &lt;p&gt;姓名:Yan Syuan&lt;/p&gt;
    	
  &lt;/section&gt;
    
  &lt;section&gt;

    &lt;h1&gt;聽不懂老師在說什麼????&lt;/h1&gt;
    
  &lt;/section&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="leo.20151113003831.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;

    &lt;h1&gt;內容大綱&lt;/h1&gt;
    &lt;ul&gt;
    &lt;li&gt;第一堂課&lt;/li&gt;
    &lt;li&gt;心得感想&lt;/li&gt;
    &lt;/ul&gt;
    			
&lt;/section&gt;
	
</t>
<t tx="leo.20151113003831.9">&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;第一堂課&lt;/h1&gt;
    &lt;p&gt;我上的第一堂課，完全不知道老師在幹嘛，只知道要跟著老師操作，也不知道為什麼要學github和python，老師要我們去看得如何做工程師那篇文章，都是英文所以大部分都看不懂&lt;/p&gt;
  
&lt;/section&gt;
				
</t>
<t tx="leo.20151113005653.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151113005653.10">&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;What Engineers Do&lt;/h1&gt;
    &lt;p&gt;工程問題通常有多個解決方案，身為一個工程師會知道怎麼的方式能更有效率的解決問題，工程師很少達到最佳的解決方案，在第一時間，一個設計可能必須重複數次。&lt;/p&gt;
    &lt;p&gt;工程師專業負責他們的設計的安全性和性能。目標是以最低的成本給定問題最簡單，最安全，最有效的設計。&lt;/p&gt;

   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113005653.11">&lt;section&gt;

    &lt;h1&gt;現代&lt;/h1&gt;
    &lt;p&gt;工程課程已逐漸演變，直到今天，它包含課題，可分為以下四種:&lt;/p&gt;
    &lt;p&gt;科學（物理，化學，數學）&lt;/p&gt;
    &lt;p&gt;工程科學&lt;/p&gt;
    &lt;p&gt;應用工程&lt;/p&gt;
    &lt;p&gt;人文與社會科學&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113005653.12">&lt;section&gt;
    &lt;h1&gt;心得感想&lt;/h1&gt;
    &lt;p&gt;開始學習翻譯如何做工程師那篇文章，沒有翻譯完，不過在這之中也學習到一些單字，知道一些做工程師所要具備的條件，第二堂課，我開始有一點點的了解老師在幹嘛了。&lt;/p&gt;
  
&lt;/section&gt;
				
</t>
<t tx="leo.20151113005653.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151113005653.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151113005653.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151113005653.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151113005653.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113005653.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113005653.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
  &lt;section&gt;

    &lt;h1&gt;第二週&lt;/h1&gt;
    &lt;p&gt;學號:40423104&lt;/p&gt;
    &lt;p&gt;姓名:Yan Syuan&lt;/p&gt;
    	
  &lt;/section&gt;
    
  &lt;section&gt;

    &lt;h1&gt;開始懂一些了，但沒有很多&lt;/h1&gt;
    
  &lt;/section&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="leo.20151113005653.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;內容大綱&lt;/h1&gt;
    &lt;p&gt;Engineers&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;Engineers&lt;/li&gt;
    &lt;li&gt;What Engineers Do&lt;/li&gt;
    &lt;li&gt;現代&lt;/li&gt;
    &lt;li&gt;工程分支&lt;/li&gt;
    &lt;li&gt;心得感想&lt;/li&gt;
    &lt;li&gt;自評成績&lt;/li&gt;
    &lt;/ul&gt;
    			
&lt;/section&gt;
	
</t>
<t tx="leo.20151113005653.9">&lt;section&gt;

    &lt;h1&gt;Engineers&lt;/h1&gt;
    &lt;p&gt;工程師是一種職業，生產人們想要的產品，他們擅長發明使用自然力量做有益的事情，科學家們路里了解大自然，而工程師的目標是生產出受經濟和社會的制約實用的產品。&lt;/p&gt;
    &lt;p&gt;工程師面對現實，以實現目標的具體問題。&lt;/p&gt;

   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113012225.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151113012225.11">&lt;section&gt;

    &lt;h1&gt;Does anyone really use Python?&lt;/h1&gt;
     &lt;ul&gt;
    &lt;li&gt;Industrial Light and Magic uses Python to help with image processing and lighting special effects&lt;/li&gt;
    &lt;li&gt;Forecast Watch.com uses Python to help with image processing and lighting special effects&lt;/li&gt;
    &lt;li&gt;Dev Net uses Python to aggregate news feeds&lt;/li&gt;
    &lt;li&gt;A student in the England made a desktop dinosaur roar every time it was mentioned on twitter with Python and Paspherry Pi&lt;/li&gt;
     &lt;/ul&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113012225.12">&lt;section&gt;
    &lt;h1&gt;Python語言&lt;/h1&gt;
    &lt;p&gt;可以在Jupyter右上角的New打開點Python3&lt;/p&gt;
    &lt;p&gt;輸入print("hello")&lt;/p&gt;
    &lt;p&gt;點run cell執行&lt;/p&gt;
    &lt;p&gt;就會跑出 hello&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113012225.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151113012225.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151113012225.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151113012225.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151113012225.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113012225.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113012225.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
  &lt;section&gt;

    &lt;h1&gt;第三週作業&lt;/h1&gt;
    &lt;p&gt;學號:40423104&lt;/p&gt;
    &lt;p&gt;姓名:Yan Syuan&lt;/p&gt;
    	
  &lt;/section&gt;
    
  &lt;section&gt;

    &lt;h1&gt;Python是一個新主流，也是一種語言&lt;/h1&gt;
    
  &lt;/section&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="leo.20151113012225.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;內容大綱&lt;/h1&gt;
    &lt;p&gt;Python&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;Python&lt;/li&gt;
    &lt;li&gt;為什麼使用Python?&lt;/li&gt;
    &lt;li&gt;Does anyone really use Python?&lt;/li&gt;
    &lt;li&gt;Python語言&lt;/li&gt;
    &lt;li&gt;心得感想&lt;/li&gt;
    &lt;li&gt;自評成績&lt;/li&gt;
    &lt;/ul&gt;
    			
&lt;/section&gt;
	
</t>
<t tx="leo.20151113012225.9">&lt;section&gt;

    &lt;h1&gt;Python&lt;/h1&gt;
    &lt;p&gt;Python是一種物件導向、直譯式的電腦程式語言，具有近二十年的發展歷史。它包含了一組功能完備的標準庫，能夠輕鬆完成很多常見的任務。它的語法簡單，與其它大多數程式設計語言使用大括弧不一樣，它使用縮進來定義語句塊。&lt;/p&gt;
    &lt;p&gt;與Scheme、Ruby、Perl、Tcl等動態語言一樣，Python具備垃圾回收功能，能夠自動管理記憶體使用，它的用途:統計、簡報、計算、或用來管理倉儲或資料。它經常被當作腳本語言用於處理系統管理任務和網路程式編寫，然而它也非常適合完成各種高階任務。Python虛擬機本身幾乎可以在所有的作業系統中運行。&lt;/p&gt;
    &lt;p&gt;Python是免費的所以可以提供給更多人使用&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113015646.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151113015646.10">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;LEO語言&lt;/h1&gt;
    &lt;p&gt;我們可以透過老師的reveal.leo檔，製作我們的投影片和作業，可以透過leo編輯器，在個人網頁中加入影片或圖片等資料。&lt;/p&gt;
    &lt;p&gt;leo的語言就是一定要記得有一個開始就要有一個結束。&lt;/p&gt;
    &lt;p&gt;可以利用html語法套用在LEO編輯器，編輯我們的資料。&lt;/p&gt;
    &lt;p&gt;例如:
    &lt;ul&gt;
    &lt;p&gt;*字代表小於大於符號
    &lt;li&gt;只要在*加入"ul"的碼，便可製出有小圓頭的清單 ，接下來在每個清單前面都要在*加入"li"，每個清單都要在li前面加入/已表示結束，然後再資料輸入後在*加入"/ul"。&lt;/li&gt;
    &lt;li&gt;在*內加入h1，打入標題文字，再以*字內加入/h1。&lt;/li&gt;
    &lt;li&gt;每個語法都以相同方式做開始與結束，就能完成投影片編輯。&lt;/li&gt;
    &lt;/ul&gt;
    &lt;/section&gt;
    
    &lt;section&gt;
    &lt;p&gt; Leo Editor 基本操作&lt;/p&gt;
    &lt;ul&gt;
    &lt;p&gt;節點&lt;/p&gt;
    &lt;li&gt;節點標題&lt;/li&gt;
    &lt;li&gt;節點內容&lt;/li&gt;
    &lt;li&gt;節點位置與從屬架構&lt;/li&gt;
    &lt;p&gt;用法&lt;/p&gt;
    &lt;li&gt;@edit用法&lt;/li&gt;
    &lt;li&gt;@path用法&lt;/li&gt;
    &lt;li&gt;@button用法&lt;/li&gt;
    &lt;li&gt;@clean用法&lt;/li&gt;
    &lt;li&gt;@language&lt;/li&gt;
    &lt;li&gt;@others&lt;/li&gt;
    &lt;/ul&gt;
    &lt;/section&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113015646.11">&lt;section&gt;

    &lt;h1&gt;Jupyter&lt;/h1&gt;
    &lt;p&gt;上課時，老師都用Jupyter使用python3。&lt;/p&gt;
    &lt;p&gt;Jupyter 是把IPython和Python解釋器剝離後的產物，將逐漸替代IPython 獨立發行。Jupyter 可以和Python 之外的程序結合，提供新的、強大的服務。例如:Ruby REPL環境IRuby 和Julia REPL環境IJulia。&lt;/p&gt;
    &lt;p&gt;我們可以利用Jupyter去學習Python語言，讓自季更熟悉Python。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113015646.12">&lt;section&gt;
    &lt;h1&gt;心得感想&lt;/h1&gt;
    &lt;p&gt;我發現瞭解完leo編輯器和每次都會被打開的Jupyter後，我越來越了解老師的上課內容了，原來我們的上課內容都一直是在用Python，覺得課程內容越來用有趣了，雖然老師每次上課的內容不一定會完全了解，但透過影片和網路查詢資料，我更清楚的知道這堂課在教什麼，和為什麼要學這堂課了，讓我對程式語言開始有興趣了。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113015646.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151113015646.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151113015646.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151113015646.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151113015646.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113015646.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113015646.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
  &lt;section&gt;

    &lt;h1&gt;第四週報告&lt;/h1&gt;
    &lt;p&gt;學號:40423104&lt;/p&gt;
    &lt;p&gt;姓名:Yan Syuan&lt;/p&gt;
    	
  &lt;/section&gt;
    
  &lt;section&gt;

    &lt;h1&gt;投影片學習&lt;/h1&gt;
    
  &lt;/section&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="leo.20151113015646.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;內容大綱&lt;/h1&gt;
    &lt;p&gt;LEO and Jupyter&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;LEO?&lt;/li&gt;
    &lt;li&gt;LEO語言&lt;/li&gt;
    &lt;li&gt;Jupyter&lt;/li&gt;
    &lt;li&gt;心得感想&lt;/li&gt;
    &lt;li&gt;自評成績&lt;/li&gt;
    &lt;/ul&gt;
    			
&lt;/section&gt;
	
</t>
<t tx="leo.20151113015646.9">&lt;section&gt;

    &lt;h1&gt;LEO?&lt;/h1&gt;
    &lt;p&gt; Leo Editor 就是採 Python 的程式方法與流程來控管其中的各節點與資料內容，&lt;/p&gt;
    &lt;p&gt; leo是一種編輯器，可以編輯網頁、製作投影片也可以當成是一個交流程式的工具&lt;/p&gt;
    &lt;p&gt;使用LEO編輯投影片和網頁時，記得要注意版本，如果是使用5.0版本，可能在5.1版本上無法開啟使用或檔案出問題。&lt;p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113154922.1">&lt;section&gt;

    &lt;h1&gt;為什麼使用Python?&lt;/h1&gt;
     &lt;ul&gt;
    &lt;li&gt;適合初學者學習程式語言&lt;/li&gt;
    &lt;li&gt;學會python的概念，可以使用相同概念在C#、C++、Javascript或Perl找關鍵詞理解他們的程式語言&lt;/li&gt;
    &lt;li&gt;無需經驗，就能學習&lt;/li&gt;
     &lt;/ul&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113154938.1">&lt;section&gt;
    &lt;h1&gt;心得感想&lt;/h1&gt;
    &lt;p&gt;看完老師要我們看的影片，雖然適用google翻譯才看懂的，可是還是對Python有了初步的了解，也越來越聽得懂老師的上課內容了，相信之後會更進步。對於程式設計更有概念，這堂課也更吸引我了。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113160707.1">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;雖然第三週還迷迷糊糊的，都跟遮老師的步驟走下去，我相信我可以當一個不一樣的工程師，給自己的分數是 :  60分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113161511.1">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;雖然課程有許多不懂的問題，但還在成長中&lt;/p&gt;
    &lt;p&gt;給自己的期許分數是80分&lt;/p&gt;
    &lt;p&gt;目前給自己的分數是50分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113171612.1">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;開始有點進入狀況了，也有點熟悉老師的上課內容。&lt;/p&gt;
    &lt;p&gt;給自己的分數:61分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113171819.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151113171819.11">&lt;section&gt;

    &lt;h1&gt;解決方法&lt;/h1&gt;
    &lt;p&gt;將有衝突的地方刪除&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;將&lt;&lt;&lt;&lt;&lt;&lt;&lt;HEAD刪除&lt;/li&gt;
    &lt;li&gt;將=======刪除 &lt;/li&gt;
    &lt;li&gt;將沒有關的節點關起來&lt;/li&gt;
    &lt;/ul&gt;
    
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113171819.12">&lt;section&gt;
    &lt;h1&gt;心得感想&lt;/h1&gt;
    &lt;p&gt;一開始在做協同時，我用老師的方法將有衝突的地方做了修正，但上傳後，我想在下載下來做資料修改時，就發現leo檔已經有問題了，我覺得很奇怪，後來同學把倉儲修好了，我才知道原來大家的協同倉儲那時候早就壞了，協同倉儲被修好了後，之後陸陸續續還是有人會把倉儲弄壞，然後又被修復，反反覆覆的被弄壞又被修復，讓我覺得我每次上傳資料時都會很緊張和小心，很怕弄壞同學的檔案，但是這也是提醒我，在做協同，絕對不能忘記一些步驟，也要注意自己有沒有不小心破壞到leo檔，覺得協同讓我有非常大的收穫。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113171819.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151113171819.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151113171819.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151113171819.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151113171819.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113171819.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113171819.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
  &lt;section&gt;

    &lt;h1&gt;第七週&lt;/h1&gt;
    &lt;p&gt;學號:40423104&lt;/p&gt;
    &lt;p&gt;姓名:Yan Syuan&lt;/p&gt;
    	
  &lt;/section&gt;
    
  &lt;section&gt;

    &lt;h1&gt;&lt;/h1&gt;
    
  &lt;/section&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="leo.20151113171819.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;內容大綱&lt;/h1&gt;
    &lt;p&gt;協同&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;協同倉儲&lt;/li&gt;
    &lt;li&gt;缺點&lt;/li&gt;
    &lt;li&gt;解決方法&lt;/li&gt;
    &lt;li&gt;心得感想&lt;/li&gt;
    &lt;li&gt;自評成績&lt;/li&gt;
    &lt;/ul&gt;
    			
&lt;/section&gt;
	
</t>
<t tx="leo.20151113171819.9">&lt;section&gt;

    &lt;h1&gt;協同倉儲&lt;/h1&gt;
    &lt;p&gt;我們可以在GitHub建立一個大家都可以去編輯的倉儲，在使用leo編輯器，讓每一個在leo裡建立自己的個人網頁，在上傳自己的網業資料，這樣就可以擁有一個大家交流資料的地方。&lt;/p&gt;
    &lt;p&gt;在user底下，將9999複製  ，改成自己的學號，在做編輯，上傳時，記得是要點使用者的那個按鍵喔
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113181636.1">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;對於協同，我更知道自己在做什麼了&lt;/p&gt;
    &lt;p&gt;這週給自己的成績:67分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113182002.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151113182002.10">&lt;section&gt;


    &lt;p&gt;利用leo編輯網頁資料，上傳到GitHub倉儲裡，再利用GitHub倉儲網址連結到個人的網頁。GitHub能廣泛運用在太多管理資料上，所以使用GitHub管理自己的資料能有效率的解決許多問題&lt;/p&gt;
    
&lt;/section&gt;
				
</t>
<t tx="leo.20151113182002.11">&lt;section&gt;

    &lt;h1&gt;Git基本操作&lt;/h1&gt;
    &lt;ul&gt;
    &lt;li&gt;git  clone 加入倉儲網址=複製倉儲資料&lt;/li&gt;
    &lt;li&gt;git  checkout 加入分支名=切換分支 &lt;/li&gt;
    &lt;li&gt;git  add  -A=拍快照到資料庫&lt;/li&gt;
    &lt;li&gt;git  commit  -m=提交&lt;/li&gt;
    &lt;li&gt;git push = 推送&lt;/li&gt;
    &lt;li&gt;git config --global user.email 帳號&lt;/li&gt;
    &lt;li&gt;git config --global user.name 使用者&lt;/li&gt;
    &lt;li&gt;git pull = 匯入資料&lt;/li&gt;
    &lt;/ul&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113182002.12">&lt;section&gt;
    &lt;h1&gt;心得感想&lt;/h1&gt;
    &lt;p&gt;一開始上課時，我都不懂我打的Git指令是什麼，透過老師上課的講解與自己練習我越來越了解每一個Git指令在做什麼，發現因為一開始的不懂造成很多問題，現在熟悉指令後，了解自己曾出過的問題是什麼，讓我更進步，錯誤雖然會讓人頭痛，但是解決錯誤可以成長，也能讓自己不會輕易放去學習。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113182002.13">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;進入狀況後，將每週作業做好，在這堂課學的東西，可以發現自己的很多不足，這樣我才會成長。&lt;/p&gt;
    &lt;p&gt;這週給自己的成績:63分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113182002.14">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151113182002.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151113182002.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151113182002.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151113182002.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113182002.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113182002.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
  &lt;section&gt;

    &lt;h1&gt;第五週&lt;/h1&gt;
    &lt;p&gt;學號:40423104&lt;/p&gt;
    &lt;p&gt;姓名:Yan Syuan&lt;/p&gt;
    	
  &lt;/section&gt;
    
  &lt;section&gt;

    &lt;h1&gt;了解~~~&lt;/h1&gt;
    
  &lt;/section&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="leo.20151113182002.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;內容大綱&lt;/h1&gt;
    &lt;p&gt;GitHub&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;GitHub使用&lt;/li&gt;
    &lt;li&gt;為什麼使用GitHub?&lt;/li&gt;
    &lt;li&gt;Git基本操作&lt;/li&gt;
    &lt;li&gt;心得感想&lt;/li&gt;
    &lt;li&gt;自評成績&lt;/li&gt;
    &lt;/ul&gt;
    			
&lt;/section&gt;
	
</t>
<t tx="leo.20151113182002.9">&lt;section&gt;

    &lt;h1&gt;GitHub使用&lt;/h1&gt;
    &lt;p&gt;要使用GitHub必需先建立帳號，建立帳號後，就能夠有效的管理倉儲及上傳資料。&lt;/p&gt;
    &lt;p&gt;每次上傳資料，GitHub會記錄每次推送的版本，如果檔案出現問題，可以利用回朔，找回還沒出問題的檔案。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151113182428.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151113182428.12">&lt;section&gt;
    &lt;h1&gt;心得感想&lt;/h1&gt;
    &lt;p&gt;這週將之前說認識的python再深入介紹一下，也將自己的問題做了紀錄，雖然在做其他軟體與程式介紹，因為我都是淺學，所以有很多的不足，因為老師給的資料很多都是英文，雖然都不是能了解得很徹底，但是我會努力的完成每週作業，提高自己的價值，做一個不一樣的工程師。&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113182428.13">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;還在前進中&lt;/p&gt;
    &lt;p&gt;這週給自己的成績:64分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151113182428.14">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151113182428.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151113182428.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151113182428.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151113182428.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113182428.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151113182428.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
  &lt;section&gt;

    &lt;h1&gt;第六週&lt;/h1&gt;
    &lt;p&gt;學號:40423104&lt;/p&gt;
    &lt;p&gt;姓名:Yan Syuan&lt;/p&gt;
    	
  &lt;/section&gt;
    
  &lt;section&gt;

    &lt;h1&gt;加油!!!!!!&lt;/h1&gt;
    
  &lt;/section&gt;
    	
&lt;/section&gt;
	
</t>
<t tx="leo.20151113182428.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section id="hw-task-one"&gt;

    &lt;h1&gt;內容大綱&lt;/h1&gt;
    &lt;p&gt;補充與問題統整&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;補充Python&lt;/li&gt;
    &lt;li&gt;問題與討論&lt;/li&gt;
    &lt;li&gt;心得感想&lt;/li&gt;
    &lt;li&gt;自評成績&lt;/li&gt;
    &lt;/ul&gt;
    			
&lt;/section&gt;
	
</t>
<t tx="leo.20151113182428.9">&lt;section&gt;
    &lt;section&gt;
    &lt;h1&gt;補充Python&lt;/h1&gt;
    &lt;p&gt;有關Python的For迴圈&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;重複迴圈
    for : for i in range(5):
              print(i)按run cell就會跑出
              0
              1
              2
              3
              4&lt;/li&gt;
    &lt;/ul&gt;
    &lt;/section&gt;
    
    &lt;section&gt;
    &lt;ul&gt;
    &lt;p&gt;限制迴圈範圍&lt;/p&gt;
    &lt;li&gt;for i in range(2, 6):
                print(i)按run cell就會跑出
                2
                3
                4
                5&lt;/li&gt;
     &lt;/section&gt;
     
     &lt;section&gt;
     &lt;p&gt;總和程式基本概念&lt;/p&gt;
     &lt;ul&gt;
     &lt;li&gt;資料呈現 : 命名規則、保留關鍵字&lt;/li&gt;
     &lt;li&gt;資料呈現 : print()→整數、浮點數、字串&lt;/li&gt;
     &lt;li&gt;數列 (list) - [1, 2, 3] [1, 2, 3, [1, 2, [1, 2, 3] ] ]&lt;/li&gt;
     &lt;li&gt;元組 (tuple) - (1, 2, 3)&lt;/li&gt;
     &lt;li&gt;字典 (dictionary) - {"a": 1, "b": 2}&lt;/li&gt;
     &lt;li&gt;重複迴圈 for&lt;/li&gt;
     &lt;li&gt;邏輯判斷 if, while&lt;/li&gt;
     &lt;/ul&gt;
     &lt;/section&gt;
    
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151116000536.1">&lt;section&gt;

    &lt;h1&gt;缺點&lt;/h1&gt;
    &lt;p&gt;協同倉儲的點就是，因為資料可以很多人做編輯，如果有人在編輯時，不小心在不知情的情況下刪除leo的資料，可能導致一些使用者的資料被刪除，嚴重的話，可能導致整個協同倉儲壞掉。&lt;/p&gt;
   
&lt;/section&gt;
				
</t>
<t tx="leo.20151116192551.1">&lt;section&gt;

    &lt;h1&gt;問題與討論&lt;/h1&gt;
    &lt;p&gt;在上完課後遇到許多問題&lt;/p&gt;
    &lt;ul&gt;
    &lt;li&gt;下載camstudio時，或一些軟體時，會下載到一些不明軟體，造成開網頁時，會有很多廣告出現。所以在下在時，資料記得要做過塞選，或使用cmd打入netstat -no的指令，可以看到目前在運作的資料&lt;/li&gt;
    &lt;li&gt;因為開啟不明的檔案，可能造成leo編輯器開補起來。例如:我下載老師的reveal2的檔案，打開leo檔，因為檔案已經壞了，導致我的leo當掉，在強制關閉後，再重開leo，就打開了。&lt;/li&gt;
    &lt;li&gt;為什麼我們在電腦教室使用的電腦有時候會ㄅㄧㄅㄧ叫呢?因為在開啟電腦時，主機板 FLASH RAM 或 EPROM 錯誤（ BIOS 損壞），這是一部份原因，網路上有許多原因，可以上網查詢。&lt;/li&gt;
    &lt;p&gt;這是我個人比較常遇到的問題喔~。&lt;/p&gt;
    &lt;/ul&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151116202754.1">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;最後一週作業了，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
    &lt;p&gt;期中作業給自己的分數:70分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151116212234.1">&lt;section&gt;

    &lt;h1&gt;工程分支&lt;/h1&gt;
    &lt;p&gt;核與航空工程最像機械工程&lt;/p&gt;
    &lt;p&gt;海軍架構是最像土木工程&lt;/p&gt;
    &lt;p&gt;石油工程對應材料和化工工程&lt;/p&gt;

&lt;/section&gt;
				
</t>
<t tx="leo.20151116213351.1">&lt;section&gt;

    &lt;h1&gt;為什麼使用GitHub?&lt;/h1&gt;
    &lt;p&gt;出社會後，如果總是把資料或要給客戶的設計圖放在隨身硬碟或電腦上，如過電腦和隨身硬碟出了問題，總不能更客戶說電腦壞了或資料檔案錯誤等跟客戶交差，這樣會影響客戶的心情或公司對你的信任，所以身為工程師，應該要將資料放入遠端，這樣會自己減少很多不必要的麻煩。&lt;/p&gt;
    &lt;p&gt;GitHub可以有有效的管理檔案，建立自己的倉儲，管理自己的資料。也可以利用協同，讓大家都可以管理一份資料。即使資料出問題了，也能有效的回朔到沒問題的資料，當客戶拿到的檔案出問題了，也能第一時間修改錯誤，讓客戶能交差。&lt;/p&gt;
    
    
&lt;/section&gt;
				
</t>
<t tx="leo.20151116223746.2"></t>
<t tx="leo.20151116223746.3">(uncached) leo.20151116202754.1
Diff...
  &lt;section&gt;
      &lt;h1&gt;自評成績&lt;/h1&gt;
-     &lt;p&gt;最後一週作業了 ，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
?               ^
+     &lt;p&gt;最後一週作業了 ，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
?               ^
      &lt;p&gt;期中作業給自己的分數:70分&lt;/p&gt;
  &lt;/section&gt;
  				
</t>
<t tx="leo.20151116223746.4">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;最後一週作業了 ，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
    &lt;p&gt;期中作業給自己的分數:70分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151116223746.5">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;最後一週作業了 ，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
    &lt;p&gt;期中作業給自己的分數:70分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151116230132.1">&lt;section&gt;

    &lt;h1&gt;Git基本操作&lt;/h1&gt;
    &lt;ul&gt;
    &lt;li&gt;git branch 分支名=建立分支&lt;/li&gt;
    &lt;li&gt;git branch=查看分支 &lt;/li&gt;
    &lt;li&gt;git  reset --hard = 回朔&lt;/li&gt;
    &lt;/ul&gt;

&lt;/section&gt;
				
</t>
<t tx="leo.20151116231945.2"></t>
<t tx="leo.20151116231945.3">(uncached) leo.20151116202754.1
Diff...
  &lt;section&gt;
      &lt;h1&gt;自評成績&lt;/h1&gt;
-     &lt;p&gt;最後一週作業了，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
?               ^
+     &lt;p&gt;最後一週作業了 ，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
?               ^
      &lt;p&gt;期中作業給自己的分數:70分&lt;/p&gt;
  &lt;/section&gt;
  				
</t>
<t tx="leo.20151116231945.4">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;最後一週作業了 ，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
    &lt;p&gt;期中作業給自己的分數:70分&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151116231945.5">&lt;section&gt;
    &lt;h1&gt;自評成績&lt;/h1&gt;
    &lt;p&gt;最後一週作業了，雖然沒有做得很好，也沒有做到自己的期望值，單是我相信，之後再努力一點一定可以達成。&lt;/p&gt;
    &lt;p&gt;期中作業給自己的分數:70分&lt;/p&gt;
&lt;/section&gt;
				
</t>
</tnodes>
</leo_file>
